field.widget.settings.multiple_selects_reference:
  type: mapping
  label: 'Multiple Selects reference widget display format settings'
  mapping:
    select_element_type:
      type: string
      label: 'Type of select form element'
    sort_options:
      type: string
      label: 'Chosen sorting of options'

field.widget.settings.multiple_selects_list:
  type: mapping
  label: 'Multiple Selects list widget display format settings'
  mapping:
    select_element_type:
      type: string
      label: 'Type of select form element'
    sort_options:
      type: string
      label: 'Chosen sorting of options'
